kind: pipeline
name: default

trigger:
  event:
    include:
    - tag

steps:

- name: build-image  
  image: plugins/docker
  settings:
    repo: zeitonline/drone-kubectl-gke
    username: zeitonline
    password:
      from_secret: dockerhub-credentials
    tags:
      - latest
      - ${DRONE_TAG}
    environment:
      VERSION: "${DRONE_TAG}"
  purge: false
  volumes:
    - name: docker
      path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: secret
name: dockerhub-credentials

get:
  path: zon/v1/dockerhub/drone
  name: token
